### ISSUE TITLE
AppVeyor for JuliaImages

### ISSUE THREAD

**Issue by timholy** [JuliaImages/meta#2]
I was looking into turning on AppVeyor for some packages in JuliaImages, and curiously I can't see any of the repos in my AppVeyor account. Does anyone have a guess as to what's wrong?

**Comment by SimonDanisch** [comment]
Did you figure it out?

**Comment by timholy** [comment]
Yeah, it's working fine now. I've enabled it mostly for packages that have seen recent activity, it's on for:
- Images
- ImageMetadata
- ImageTransformations
- ImageCore
- ImageFiltering
- ImageFeatures

Others should also be able to activate other packages, but I'm also happy to turn additional repos upon request.
