### ISSUE TITLE
Pinned packages

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/meta#4]
We have the ability to pin a few packages here: https://github.com/JuliaImages, which helps visibility of the most relevant user facing packages, so that it is easier for a user to decide what is end-user facing and what is a back-end package. We should pin 2-3 packages. 

`Images.jl` is the obvious choice (and I took the liberty to pin it). Any other suggestions?

Personally I think `Images.jl`, `TestImages.jl` and `ImageInTerminal.jl` would make a useful selection. Most of the others either get reexported by Images.jl or are still in development

**Comment by Evizero** [comment]
I'll just go ahead and pin them. If anyone disagrees, please feel free to undo it or post here

**Comment by timholy** [comment]
Those sounds like good choices. I didn't know about this capability.

Once we register & tag ImageFeatures, that's another obvious choice.

**Comment by Evizero** [comment]
Oh wow, talk about timing. We must have posted at pretty much the same exact time

> Once we register & tag ImageFeatures, that's another obvious choice.

Good idea
