### ISSUE TITLE
ImageDistances.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/meta#5]
I would like to ask you if I can create an ImageDistances.jl package in the organization? Would that be useful to you? I see myself computing distances between images all the time, and yet I cannot contribute the code I have to Distances.jl because distances there are between one-dimensional vectors only, AFAIK.

Please let me know what do you think about it, and I will try to find the time to implement it in the new Images.jl API.

P.S.: Should we have a gitter chat room for everything image processing in Julia?

**Comment by timholy** [comment]
How big of a package are you thinking? If it's just a few methods, it could be added to Images.jl. If it's a large thing, then sure, a separate repo might be a good idea. You could probably move a couple of methods in the current Images.jl to it.

**Comment by juliohm** [comment]
Thanks Tim, it would be just a few methods as you said. My initial idea of creating a package was more to motivate others to think of distances between images as a first-class concept. I will follow your suggestion and keep it inside Images.jl.

What about the gitter chat room, do we have one already?

**Comment by timholy** [comment]
I don't know of one. I'm not even sure what's involved, I've never used one. I'm not opposed if others want to do the work of setting it up.

**Comment by juliohm** [comment]
Thanks Tim, I can figure this out.
