### ISSUE TITLE
Transfer VideoIO.jl to JuliaImage

### ISSUE THREAD

**Issue by kmsquire** [JuliaImages/meta#7]
(from https://github.com/orgs/JuliaImages/teams/founders/discussions/4)

Would people be okay if I transfered VideoIO.jl to JuliaImages? I put this idea forward about 2-3 years ago, and at the time, people here were okay with it, but I never pulled the trigger.

To be clear, the only purpose I see for doing this is for increased visibility, and the potential for cleaner interaction with the rest of JuliaImages. I would still do my best to be involved at least as much as I am now with the project (which is to say, enough to keep it alive), and I have no illusion that transferring it to JuliaImages will magically give it a bunch of new maintainers. :-) But I do hope that it might get a little more love.

If you all are on board, I'll do the transfer. (If you think that there isn't much use, please speak up--I can continue hosting it on my personal account until I find someone to take it over.)

**Comment by Evizero** [comment]
I don't really have an opinion. From the sound of it though, wouldn't JuliaIO be more appropriate?

**Comment by kmsquire** [comment]
> From the sound of it though, wouldn't JuliaIO be more appropriate?

Yep, that would probably make more sense.  Thanks for the suggestion!

I'll work on removing the dependency on Images.jl, then try to transfer it there.
